# Site settings
name: Saul Lustgarten
description: "entrepreneur. mba @ mit"
url: "slustgarten.github.io"


# Delete the lines you don't need
# about 5 elements are recomended
github_username:  slustgarten
facebook_username: lustgarten
twitter_username: slustgarten
linkedin_username: slustgarten
instagram_username:  slustgarten
stack_of_username: your_stack_overflow_account_id_number_goes_here
reddit_username: your_reddit_username_goes_here
medium_username:  slustgarten
blog_url: "/blog"
email: slustgarten@gmail.com
public_key_url: ""


avatar: yes
#avatar_img_path: "imgs/avatar.jpg""
# You can link to your GitHub image. That way it will get updated
# automatically whenever you change your GitHub profile picture
avatar_img_path: "https://avatars0.githubusercontent.com/u/247529?v=3&u=79b9016530b8d7e368087ee40bfb170694a88ec6&s=140"


front_img: yes
#front_img_path: "imgs/background.jpg"
front_img_path: "https://hd.unsplash.com/photo-1463527882365-18201e85a091"


favicon_img: yes
favicon_img_path: "imgs/favicon.ico"
#favicon_img_path: "https://external.url/favicon.ico"


# Build settings
markdown: kramdown
permalink: pretty
